export type Suburb = {
    name: string;
    hint: string;
    letters: number;
}

export const guessList: Suburb[] = [
    { name: "Stirling", hint: "Named after the first Governor of WA", letters: 8 },
    { name: "Hawker", hint: "Belconnen-area suburb with local shops", letters: 6 },
    { name: "Macnamara", hint: "Quiet, mainly residential suburb", letters: 9 },
    { name: "Page", hint: "Small suburb with a neighbourhood shopping strip", letters: 4 },
    { name: "Bruce", hint: "Northside suburb near the stadium and university precinct", letters: 5 },
    { name: "Farrer", hint: "Established suburb with leafy streets", letters: 6 },
    { name: "Scullin", hint: "Older northside suburb with a local community feel", letters: 7 },
    { name: "Gowrie", hint: "Residential suburb close to other Belconnen suburbs", letters: 6 },
    { name: "Bonython", hint: "Southern suburb on Canberra's outer edge", letters: 8 },
    { name: "Gordon", hint: "Suburban area with a village-style shopping strip", letters: 6 },
    { name: "Belconnen", hint: "Major town centre on Canberra's northside", letters: 9 },
    { name: "Theodore", hint: "Suburb in the Tuggeranong area", letters: 8 },
    { name: "Whitlam", hint: "Relatively new residential suburb", letters: 7 },
    { name: "Macarthur", hint: "Suburban area near Woden/Isabella region", letters: 9 },
    { name: "Amaroo", hint: "Gungahlin suburb with a village shopping centre", letters: 6 },
    { name: "Taylor", hint: "Newer residential suburb in the north", letters: 6 },
    { name: "Tharwa", hint: "Small village on Canberra's southern rural fringe", letters: 6 },
    { name: "Spence", hint: "Established northside suburb with local amenities", letters: 6 },
    { name: "Gungahlin", hint: "Rapidly growing district and town centre to the north", letters: 9 },
    { name: "Fadden", hint: "Suburb in the Tuggeranong region", letters: 6 },
    { name: "Crace", hint: "Newer suburb on the Gungahlin outskirts", letters: 5 },
    { name: "Palmerston", hint: "Outer northern suburb with developing facilities", letters: 10 },
    { name: "O'Malley", hint: "Inner south suburb close to the lake and parklands", letters: 8 },
    { name: "Florey", hint: "Residential suburb with local shops", letters: 6 },
    { name: "Throsby", hint: "Newer northside suburb near Gungahlin", letters: 7 },
    { name: "Fyshwick", hint: "Industrial and retail precinct just east of the city", letters: 8 },
    { name: "Nicholls", hint: "Gungahlin-adjacent suburb with established streets", letters: 8 },
    { name: "Downer", hint: "Inner north suburb with a neighbourhood feel", letters: 6 },
    { name: "Holt", hint: "Western suburb with a quiet residential atmosphere", letters: 4 },
    { name: "Mawson", hint: "Woden Valley suburb with established homes", letters: 6 },
    { name: "Kingston", hint: "Inner south lakeside precinct with shops and cafes", letters: 8 },
    { name: "Symonston", hint: "Area with a mix of uses near the airport and industrial zones", letters: 9 },
    { name: "Chisholm", hint: "Tuggeranong suburb with residential streets", letters: 8 },
    { name: "Russell", hint: "Defence and government area adjacent to the city", letters: 7 },
    { name: "Kaleen", hint: "North Canberra suburb with parks and local shops", letters: 6 },
    { name: "Turner", hint: "Inner north suburb close to the city and lake", letters: 6 },
    { name: "Uriarra Village", hint: "Small community on the western rural fringe", letters: 14 },
    { name: "Wright", hint: "Suburb in the Molonglo/Weston Creek area", letters: 6 },
    { name: "Molonglo", hint: "Newer developing district on Canberra's western side", letters: 8 },
    { name: "Weston", hint: "Weston Creek suburb with local shops and parks", letters: 6 },
    { name: "Banks", hint: "Southern suburb in the Tuggeranong/Woden fringe", letters: 5 },
    { name: "Fraser", hint: "Belconnen-area suburb with family homes", letters: 6 },
    { name: "Gilmore", hint: "South Canberra suburb with established amenities", letters: 7 },
    { name: "Casey", hint: "Northern suburb on Canberra's outskirts", letters: 5 },
    { name: "Ngunnawal", hint: "Gungahlin suburb with a strong community focus", letters: 9 },
    { name: "Barton", hint: "Close to the Parliamentary Triangle and government offices", letters: 6 },
    { name: "Macquarie", hint: "Bordering parklands and the lake in the inner north", letters: 9 },
    { name: "Hall", hint: "Small village north of the city with a rural feel", letters: 4 },
    { name: "Narrabundah", hint: "Inner south suburb popular for leafy streets", letters: 11 },
    { name: "Yarralumla", hint: "Prestigious inner south suburb near the lake", letters: 10 },
    { name: "Strathnairn", hint: "Semi-rural suburb with community spaces on the west", letters: 11 },
    { name: "Ainslie", hint: "Inner north suburb at the foot of Mount Ainslie", letters: 7 },
    { name: "Parkes", hint: "Contains the Parliamentary Triangle and national institutions", letters: 6 },
    { name: "Evatt", hint: "Belconnen suburb with local parks", letters: 5 },
    { name: "O'Connor", hint: "Inner north suburb with a busy local dining strip", letters: 8 },
    { name: "Richardson", hint: "Established Tuggeranong suburb with community facilities", letters: 10 },
    { name: "Higgins", hint: "Belconnen-area suburb with quiet streets", letters: 7 },
    { name: "Greenway", hint: "Suburb in the Woden/Tuggeranong corridor", letters: 8 },
    { name: "Franklin", hint: "Gungahlin suburb with a lively town centre", letters: 8 },
    { name: "Garran", hint: "Woden Valley suburb close to hospitals and amenities", letters: 6 },
    { name: "Watson", hint: "Inner north suburb near local shops and schools", letters: 6 },
    { name: "City", hint: "This one's easy ;)", letters: 4 },
    { name: "Charnwood", hint: "Belconnen suburb with family-friendly parks", letters: 9 },
    { name: "Forrest", hint: "Leafy, inner south suburb near the Parliamentary area", letters: 7 },
    { name: "Melba", hint: "Belconnen suburb with suburban streets and parks", letters: 5 },
    { name: "Wanniassa", hint: "Major Tuggeranong suburb with established shopping", letters: 9 },
    { name: "Dunlop", hint: "Northwest suburb on Canberra's outer edge", letters: 6 },
    { name: "Hughes", hint: "Quiet inner south suburb with leafy streets", letters: 6 },
    { name: "Curtin", hint: "Inner south suburb with a local shopping village", letters: 6 },
    { name: "Isabella Plains", hint: "Tuggeranong suburb with residential amenities", letters: 14 },
    { name: "Reid", hint: "Inner city suburb close to the lake and cultural institutions", letters: 4 },
    { name: "Forde", hint: "Gungahlin suburb with newer housing", letters: 5 },
    { name: "Calwell", hint: "Tuggeranong suburb with suburban streets", letters: 7 },
    { name: "Denman Prospect", hint: "Growing suburb in the Molonglo Valley development", letters: 14 },
    { name: "Oaks Estate", hint: "Small historic community beside the Jerrabomberra Wetlands", letters: 11 },
    { name: "Isaacs", hint: "Inner south suburb with quiet, leafy blocks", letters: 6 },
    { name: "Moncrieff", hint: "Gungahlin suburb with family-oriented streets", letters: 9 },
    { name: "Hume", hint: "Industrial and business precinct near the airport", letters: 4 },
    { name: "Duffy", hint: "Western suburb with a village feel", letters: 5 },
    { name: "Hackett", hint: "Inner north suburb with tree-lined streets", letters: 7 },
    { name: "McKellar", hint: "Belconnen suburb with homes and parkland", letters: 8 },
    { name: "Lyons", hint: "Woden Valley suburb with local shops", letters: 5 },
    { name: "Griffith", hint: "Inner south suburb known for cafes and gardens", letters: 8 },
    { name: "Canberra Airport", hint: "The city's main airport and surrounding precinct", letters: 14 },
    { name: "Waramanga", hint: "Western suburb with suburban streets and parks", letters: 9 },
    { name: "Coombs", hint: "Newer suburb in the Molonglo Valley area", letters: 6 },
    { name: "Weetangera", hint: "Established northside suburb with local facilities", letters: 10 },
    { name: "Jacka", hint: "Gungahlin suburb with newer housing estates", letters: 5 },
    { name: "Monash", hint: "Woden Valley suburb with parkland nearby", letters: 6 },
    { name: "Harrison", hint: "Gungahlin suburb with a developing town centre", letters: 8 },
    { name: "Kambah", hint: "One of Tuggeranong's largest suburbs", letters: 6 },
    { name: "Lyneham", hint: "Inner north suburb close to the city and Dickson", letters: 7 },
    { name: "Giralang", hint: "Belconnen suburb with parks and primary schools", letters: 8 },
    { name: "Bonner", hint: "Gungahlin suburb with family-friendly streets", letters: 6 },
    { name: "Cook", hint: "Inner north suburb with a small shopping village", letters: 4 },
    { name: "Aranda", hint: "Belconnen suburb beside black mountain parkland", letters: 6 },
    { name: "Rivett", hint: "Woden Valley suburb with tree-lined streets", letters: 6 },
    { name: "Conder", hint: "Tuggeranong suburb with river and parkland nearby", letters: 6 },
    { name: "Deakin", hint: "Inner south suburb close to embassies and bushland", letters: 6 },
    { name: "Lawson", hint: "Belconnen-area suburb with residential streets", letters: 6 },
    { name: "Pearce", hint: "Woden Valley suburb with local amenities", letters: 6 },
    { name: "Dickson", hint: "Inner north suburb known for eateries and shops", letters: 7 },
    { name: "Pialligo", hint: "Rural precinct near the airport with small holdings", letters: 8 },
    { name: "Flynn", hint: "Suburb with a residential character in the north", letters: 5 },
    { name: "Holder", hint: "Woden Valley suburb with local parks", letters: 6 },
    { name: "Braddon", hint: "Inner city precinct with cafes, bars and shops", letters: 7 },
    { name: "Mitchell", hint: "Industrial area on the northside", letters: 8 },
    { name: "Phillip", hint: "Woden/Belconnen fringe with commercial centres", letters: 7 },
    { name: "Latham", hint: "Belconnen suburb with local reserves", letters: 6 },
    { name: "Oxley", hint: "Tuggeranong suburb with quiet residential streets", letters: 5 },
    { name: "Torrens", hint: "Woden Valley suburb with mature gardens", letters: 7 },
    { name: "Acton", hint: "Home to the ANU precinct and close to the lake", letters: 5 },
    { name: "Campbell", hint: "Inner north suburb bordering the Parliamentary area", letters: 8 },
    { name: "Chapman", hint: "Inner south suburb with leafy streets", letters: 7 },
    { name: "Capital Hill", hint: "Where Parliament House sits", letters: 11 },
    { name: "Macgregor", hint: "Belconnen suburb with family homes and parks", letters: 9 },
    { name: "Fisher", hint: "Suburb in the Enclosed Woden area with suburban streets", letters: 6 },
    { name: "Beard", hint: "Semi-rural area near the airport precinct", letters: 5 },
    { name: "Red Hill", hint: "Inner south suburb with elevated outlooks and green space", letters: 8 },
    { name: "Chifley", hint: "Woden Valley suburb with established homes", letters: 7 }
];