export type Suburb = {
    name: string;
    hint: string;
    letters: number;
}

export const guessList: Suburb[] = [
    { name: "Stirling", hint: "Named after the first Governor of WA", letters: 8 },
    { name: "Hawker", hint: "", letters: 6 },
    { name: "Macnamara", hint: "", letters: 9 },
    { name: "Page", hint: "", letters: 4 },
    { name: "Bruce", hint: "", letters: 5 },
    { name: "Farrer", hint: "", letters: 6 },
    { name: "Scullin", hint: "", letters: 7 },
    { name: "Gowrie", hint: "", letters: 6 },
    { name: "Bonython", hint: "", letters: 8 },
    { name: "Gordon", hint: "", letters: 6 },
    { name: "Belconnen", hint: "", letters: 9 },
    { name: "Theodore", hint: "", letters: 8 },
    { name: "Whitlam", hint: "", letters: 7 },
    { name: "Macarthur", hint: "", letters: 9 },
    { name: "Amaroo", hint: "", letters: 6 },
    { name: "Taylor", hint: "", letters: 6 },
    { name: "Tharwa", hint: "", letters: 6 },
    { name: "Spence", hint: "", letters: 6 },
    { name: "Gungahlin", hint: "", letters: 9 },
    { name: "Fadden", hint: "", letters: 6 },
    { name: "Crace", hint: "", letters: 5 },
    { name: "Palmerston", hint: "", letters: 10 },
    { name: "O'Malley", hint: "", letters: 8 },
    { name: "Florey", hint: "", letters: 6 },
    { name: "Throsby", hint: "", letters: 7 },
    { name: "Fyshwick", hint: "", letters: 8 },
    { name: "Nicholls", hint: "", letters: 8 },
    { name: "Downer", hint: "", letters: 6 },
    { name: "Holt", hint: "", letters: 4 },
    { name: "Mawson", hint: "", letters: 6 },
    { name: "Kingston", hint: "", letters: 8 },
    { name: "Symonston", hint: "", letters: 9 },
    { name: "Chisholm", hint: "", letters: 8 },
    { name: "Russell", hint: "", letters: 7 },
    { name: "Kaleen", hint: "", letters: 6 },
    { name: "Turner", hint: "", letters: 6 },
    { name: "Uriarra Village", hint: "", letters: 14 },
    { name: "Wright", hint: "", letters: 6 },
    { name: "Molonglo", hint: "", letters: 8 },
    { name: "Weston", hint: "", letters: 6 },
    { name: "Banks", hint: "", letters: 5 },
    { name: "Fraser", hint: "", letters: 6 },
    { name: "Gilmore", hint: "", letters: 7 },
    { name: "Casey", hint: "", letters: 5 },
    { name: "Ngunnawal", hint: "", letters: 9 },
    { name: "Barton", hint: "", letters: 6 },
    { name: "Macquarie", hint: "", letters: 9 },
    { name: "Hall", hint: "", letters: 4 },
    { name: "Narrabundah", hint: "", letters: 11 },
    { name: "Yarralumla", hint: "", letters: 10 },
    { name: "Strathnairn", hint: "", letters: 11 },
    { name: "Ainslie", hint: "", letters: 7 },
    { name: "Parkes", hint: "", letters: 6 },
    { name: "Evatt", hint: "", letters: 5 },
    { name: "O'Connor", hint: "", letters: 8 },
    { name: "Richardson", hint: "", letters: 10 },
    { name: "Higgins", hint: "", letters: 7 },
    { name: "Greenway", hint: "", letters: 8 },
    { name: "Franklin", hint: "", letters: 8 },
    { name: "Garran", hint: "", letters: 6 },
    { name: "Watson", hint: "", letters: 6 },
    { name: "City", hint: "This one's easy ;)", letters: 4 },
    { name: "Charnwood", hint: "", letters: 9 },
    { name: "Forrest", hint: "", letters: 7 },
    { name: "Melba", hint: "", letters: 5 },
    { name: "Wanniassa", hint: "", letters: 9 },
    { name: "Dunlop", hint: "", letters: 6 },
    { name: "Hughes", hint: "", letters: 6 },
    { name: "Curtin", hint: "", letters: 6 },
    { name: "Isabella Plains", hint: "", letters: 14 },
    { name: "Reid", hint: "", letters: 4 },
    { name: "Forde", hint: "", letters: 5 },
    { name: "Calwell", hint: "", letters: 7 },
    { name: "Denman Prospect", hint: "", letters: 14 },
    { name: "Oaks Estate", hint: "", letters: 11 },
    { name: "Isaacs", hint: "", letters: 6 },
    { name: "Moncrieff", hint: "", letters: 9 },
    { name: "Hume", hint: "", letters: 4 },
    { name: "Duffy", hint: "", letters: 5 },
    { name: "Hackett", hint: "", letters: 7 },
    { name: "McKellar", hint: "", letters: 8 },
    { name: "Lyons", hint: "", letters: 5 },
    { name: "Griffith", hint: "", letters: 8 },
    { name: "Canberra Airport", hint: "", letters: 14 },
    { name: "Waramanga", hint: "", letters: 9 },
    { name: "Coombs", hint: "", letters: 6 },
    { name: "Weetangera", hint: "", letters: 10 },
    { name: "Jacka", hint: "", letters: 5 },
    { name: "Monash", hint: "", letters: 6 },
    { name: "Harrison", hint: "", letters: 8 },
    { name: "Kambah", hint: "", letters: 6 },
    { name: "Lyneham", hint: "", letters: 7 },
    { name: "Giralang", hint: "", letters: 8 },
    { name: "Bonner", hint: "", letters: 6 },
    { name: "Cook", hint: "", letters: 4 },
    { name: "Aranda", hint: "", letters: 6 },
    { name: "Rivett", hint: "", letters: 6 },
    { name: "Conder", hint: "", letters: 6 },
    { name: "Deakin", hint: "", letters: 6 },
    { name: "Lawson", hint: "", letters: 6 },
    { name: "Pearce", hint: "", letters: 6 },
    { name: "Dickson", hint: "", letters: 7 },
    { name: "Pialligo", hint: "", letters: 8 },
    { name: "Flynn", hint: "", letters: 5 },
    { name: "Holder", hint: "", letters: 6 },
    { name: "Braddon", hint: "", letters: 7 },
    { name: "Mitchell", hint: "Industrial area on the northside", letters: 8 },
    { name: "Phillip", hint: "", letters: 7 },
    { name: "Latham", hint: "", letters: 6 },
    { name: "Oxley", hint: "", letters: 5 },
    { name: "Torrens", hint: "", letters: 7 },
    { name: "Acton", hint: "", letters: 5 },
    { name: "Campbell", hint: "", letters: 8 },
    { name: "Chapman", hint: "", letters: 7 },
    { name: "Capital Hill", hint: "", letters: 11 },
    { name: "Macgregor", hint: "", letters: 9 },
    { name: "Fisher", hint: "", letters: 6 },
    { name: "Beard", hint: "", letters: 5 },
    { name: "Red Hill", hint: "", letters: 8 },
    { name: "Chifley", hint: "", letters: 7 }
];
